##################################################
# _____                   _   _       _______ _  #
#|  ___|                 | | (_)     | | ___ \ | #
#| |__ ___ ___  ___ _ __ | |_ _  __ _| | |_/ / | #
#|  __/ __/ __|/ _ \ '_ \| __| |/ _` | |  __/| | #
#| |__\__ \__ \  __/ | | | |_| | (_| | | |   | | #
#\____/___/___/\___|_| |_|\__|_|\__,_|_\_|   |_| #
#                                                #
#================================================#
#This Plugin was created by RémiTheGinger        #
#For his server                                  #
#!! This is an open sources Plugin !!            #
##################################################

#Servers default Gamemode for players
#If you are setting this manually make sure to write the Gamemode in caps (ex : CREATIVE)
#Default : SURVIVAL
defaultGameMode : SURVIVAL

#Choose where to display plugin messages for players
#Option:
#   - chat
#   - actionbar
#Default: actionbar
message_displaymode: actionbar

#Choose if a player can get another player's head on kill
#By default, players have a 15% chance of having a head (changeable at head_chance)
#Default: true
head_drop: true
#Chance pourcentage to drop the head
#this is ignored if head_drop is set to false
#Default: 15
head_chance: 15

#############################
# SERVER MOTD CONFIGURATION #
#############################

#Colorize the server MOTD
#Use the bukkit color codes in the server.properties to colorize the MOTD if this is set to true
#Default: true
colorize_motd: true
#Show the MOTD on the Player Tab list
#This will only be colorized if the 'colorize_motd' is set to true
#Default: true
tablist_motd : true